version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodemls
    overwrite: true
hooks:
  BeforeInstall: 
    - location: before-install.sh
      timeout: 300
  AfterInstall:
    - location: after-install.sh
      timeout: 300
  ApplicationStart:
    - location: application-start.sh
      timeout: 300
